routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.pages.home.index');
})->name('homepage');

Route::get('about', function () {
    return view('frontend.pages.about.index');
})->name('about');

Route::get('items', function () {
    return view('frontend.pages.products.index');
})->name('product');

Route::get('store', function () {
    return view('frontend.pages.store.index');
})->name('store');

Auth::routes();

Route::get('home', 'Backend\HomeController@index')->name('home');

Route::resource('cashier', 'Backend\CashierController')->middleware('auth');

Route::resource('products', 'Backend\ProductController')->middleware('auth');

Route::resource('inventory', 'Backend\InventoryController')->middleware('auth')->parameters(['inventory'=>'product']);

Route::resource('categories', 'Backend\ProductCategoryController')->middleware('auth');

Route::resource('users', 'Backend\UserController')->middleware('auth');

Route::resource('orders', 'Backend\OrderController')->middleware('auth');

Route::resource('branches', 'Backend\BranchController')->middleware('auth');

Route::resource('transactions', 'Backend\TransactionController')->middleware('auth');

Route::get('users-search', 'Backend\UserController@index')->name('users.search');

app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Auth;

class Transaction extends Model
{
    protected $fillable = [
        'name',
        'is_served',
        'cash',
        'change',
        'total_amount',
        'discount',
        'branch_id'
    ];

    protected $with = [ 'orders' ];

    public function orders()
    {
        return $this->belongsToMany(Order::class);
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }

    public function getCreatedAtAttribute($value){
        return Carbon::parse($value)->toDayDateTimeString();
    }
}

app/Http/Controllers/Backend/TransactionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Transaction;
use Carbon\Carbon;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::paginate(5);

        return view('backend.pages.transactions.index', compact('transactions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::find($id);

        return view('backend.pages.transactions.show', compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/pages/transactions/index.blade.php
@extends('backend.layouts.app')

@section('css')
    <style>
        thead > tr > td{
            font-weight: bold;
        }
    </style>
@endsection
@section('content')
<div class="card">
    <div class="card-header">Transactions</div>
    <div class="card-body">
       @if($transactions->isNotEmpty())
       <div class="table">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>Transaction Date</td>
                        <td>Total Amount</td>
                        <td>Cash</td>
                        <td>Change</td>
                        <td>Discount</td>
                        <td>Branch</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->created_at }}</td>
                        <td>{{ $transaction->total_amount }}</td>
                        <td>{{ $transaction->cash }}</td>
                        <td>{{ $transaction->change }}</td>
                        <td>{{ $transaction->discount }}</td>
                        <td>{{ $transaction->branch->name }}</td>
                        <td>
                            <a href="{{ route('transactions.show', $transaction->id) }}"><button type="button" class="btn btn-info">View</button></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {{ $transactions->links() }}
        @else
        <center>
            <h2>No transactions yet...</h2>
        </center>
        @endif
    </div>
</div> 
@endsection

resources/views/backend/pages/transactions/show.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Show Transaction</div>
    <div class="modal-body printDiv">
        <center>
            <img src="{{ asset('assets/images/maya-logo.jpg') }}" alt="" width="100px">
        <br><br>
        <table>
            <tbody class="table">
                @foreach($transaction->orders as $order)
                <tr>
                    <td>
                        {{ $order->product->name }}
                    </td>
                    <td>
                        {{ $order->quantity ." X ". $order->price}}
                    </td>
                    <td>
                        {{ $order->quantity * $order->price }}
                    </td>
                </tr>
                @endforeach
                <tr>
                    <td>
                        <b>Total</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ $transaction->total_amount + $transaction->discount }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>12% VAT</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ ($transaction->total_amount + $transaction->discount) * 0.12 }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>20% Discount</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ ($transaction->total_amount + $transaction->discount) * 0.20 }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Total Amount</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ $transaction->total_amount }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Cash</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ $transaction->cash }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Change</b>
                    </td>
                    <td colspan="2">
                        <span class="pull-right"> {{ $transaction->change }} </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <center>
                            <button class="btn btn-success" v-on:click="printReceipt">Print Receipt</button>
                        </center>
                    </td>
                </tr>
            </tbody>
        </table>
        </center>
    </div>
</div> 
@endsection

@section('js')
<script src="{{ asset('js/cashier.js') }}"></script>
@endsection